name: BidNet

services:
  bidnet-db:
    image: mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "SELECT 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  # bidnet-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - ConnectionStrings__Default=Server=db;Database=master;User Id=sa;Password=YourStrong@Passw0rd;
  #   ports:
  #     - "5000:80"
  #   depends_on:
  #     - db:
  #       condition: service_healthy

volumes:
  db_data:
